export const NUM_OF_QUESTIONS = 10;
export const POINTS_EARNED_PER_QUESTION = 10;
export const ROWS_AT_LEADERBOARD = 10;
export const QUESTIONS_URL = 'https://opentdb.com/api.php?amount=10&type=multiple';
export const QUESTION_HEADER = 'question';
export const CORRECT_HEADER = 'correct_answer';
export const INCORRECT_HEADER = 'incorrect_answers';
export const RANKING_HEADER = 'Rank';
export const USERNAME_HEADER = 'Username';
export const POINTS_HEADER = 'Points';
export const DATE_HEADER = 'Date played';
